### ISSUE TITLE
Wrong arch detection - node: cannot execute binary file error

### ISSUE THREAD

**Issue by zaety777** [Osiris-Team/HBrowser#14]
The following issues occurred while executing in centos7 environment.
![image](https://user-images.githubusercontent.com/11039438/202630434-a7a77ff3-cccf-406e-a16b-fa0eeaf04711.png)

![image](https://user-images.githubusercontent.com/11039438/202630303-5c8e0ca8-a476-4d3e-9484-447847f4c40b.png)

![image](https://user-images.githubusercontent.com/11039438/202632109-70db448b-8bb0-4a4a-97b6-1c202f5621a3.png)

Could you give me some help?

**Comment by Osiris-Team** [comment]
@zaety777 looks like it detects the arch wrong. 
Thanks for reporting I'll look into it asap.

**Comment by Osiris-Team** [comment]
Try 2.4.2. Should be fixed. Delete the node folder before though.

**Comment by zaety777** [comment]
Thank you for solving it quickly. Have a warm end of the year.
