### ISSUE TITLE
Click with promise.All

### ISSUE THREAD

**Issue by nocelab** [Osiris-Team/HBrowser#8]
I'm testing site navigation with Playwright `codegen` mode (https://playwright.dev/docs/codegen) and I note that some click produce something like:

```js
await Promise.all([
   page.click('text=Confirm'),
   page.waitForNavigation(),
]);
```

I have a spefic page where this is importat because of some async RestAPI calls.
How could be handle it with HBrowser?

**Comment by Osiris-Team** [comment]
Something like this should do it i think:
```java
playwrightWindow.getJsContext().executeJavaScript(""+
"await Promise.all([\n"+
  " page.click('text=Confirm'),\n"+
   "page.waitForNavigation(),\n"+
]);");
```
